#!/bin/bash
# +----------------------------------------------------------------------------+
# | MM7D v0.1 * RH/T measuring device                                          |
# | Copyright (C) 2020-2023 Pozsár Zsolt <pozsarzs@gmail.com>                  |
# | clone                                                                      |
# | Clone libraries from Github                                                |
# +----------------------------------------------------------------------------+

git clone https://github.com/adafruit/Adafruit_Sensor
git clone https://github.com/adafruit/DHT-sensor-library
git clone https://github.com/emelianov/modbus-esp8266
git clone https://github.com/esp8266/Arduino
git clone https://github.com/aharshac/StringSplitter
