#!/bin/bash
# +----------------------------------------------------------------------------+
# | MM7D v0.1 * Air quality measuring device                                   |
# | Copyright (C) 2020 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>            |
# | clone                                                                      |
# | Clone libraries from Github                                                |
# +----------------------------------------------------------------------------+

git clone https://github.com/adafruit/Adafruit_Sensor.git
git clone https://github.com/adafruit/DHT-sensor-library.git
